CREATE TABLE IF NOT EXISTS USERS_NL
(login VARCHAR(64) PRIMARY KEY,passwd VARCHAR(64));
CREATE TABLE IF NOT EXISTS USER_ROLES_NL(login VARCHAR(64), role VARCHAR(32));
DELETE from USER_ROLES_NL;
DELETE from USERS_NL;

